### ISSUE TITLE
No examples

### ISSUE THREAD

**Issue by readnotify** [perlancar/perl-JSON-Color#2]
Says this right at the start:
```
Pick a color theme, ... for example ColorTheme::Lens::Lighten
```
but without any hint or clue as to where that goes or how to use it to change anything.

The default colours are unreadable - dark purple, light purple, and green?  Seriously??

**Comment by perlancar** [comment]
I added a couple of examples in Synopsis (commit e50c333) as well as another color theme (commit 2ea00ea).

Released 0.134.
